# Generated by Django 3.0.3 on 2020-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamaritanState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=20, unique=True, verbose_name='driver')),
                ('state', models.CharField(choices=[('nr', 'no-request'), ('wd', 'waiting-for-driver'), ('cd', 'currently-driving')], max_length=2, verbose_name='nr')),
            ],
        ),
    ]
