# Generated by Django 2.2.4 on 2020-02-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamaritanKeyDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.BooleanField(default=False, verbose_name='left')),
                ('right', models.BooleanField(default=False, verbose_name='right')),
                ('forward', models.BooleanField(default=False, verbose_name='forward')),
                ('backward', models.BooleanField(default=False, verbose_name='backward')),
            ],
        ),
    ]
